spring:
  application:
    name: musinsa-homework
  threads:
    virtual:
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - name: 브랜드 정보 API
        url: /swagger/brandapi.yml
      - name: 제품 정보 API
        url: /swagger/productapi.yml
      - name: 가격정보 API
        url: /swagger/priceapi.yml
    path: /swagger-ui.html
