spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=MySQL
    username: sa
    password:
  data:
    redis:
      host: redis
      port: 6379
      client-type: lettuce
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
  sql:
    init:
      mode: always
      data-locations: classpath:dml.sql
      schema-locations: classpath:ddl.sql
server:
  port: 8080
