spring:
  application:
    name: musinsa-homework
  threads:
    virtual:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=MySQL
    username: sa
    password:
  data:
    redis:
      host: localhost
      port: 6379
      client-type: lettuce
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
  sql:
    init:
      mode: always
      data-locations: classpath:dml.sql
      schema-locations: classpath:ddl.sql
server:
  port: 8080


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - name: 브랜드 정보 API
        url: /swagger/brandapi.yml
      - name: 제품 정보 API
        url: /swagger/productapi.yml
      - name: 가격정보 API
        url: /swagger/priceapi.yml
    path: /swagger-ui.html
